#!perl

# DATE
# VERSION

use 5.010001;
use strict;
use warnings;
use Log::ger;

use Perinci::CmdLine::Any;
use Perinci::CmdLineX::CommonOptions::SelfUpgrade;

my $prefix = "/App/bwk/mn/";

my $cli = Perinci::CmdLine::Any->new(
    url => $prefix,
    log => 1,
    pass_cmdline_object => 1,
    subcommands => {
        'status'    => { url => "${prefix}status", },
    },
);
Perinci::CmdLineX::CommonOptions::SelfUpgrade->apply_to_object($cli);
$cli->run;

# ABSTRACT: Some commands to manage Bulwark masternode
# PODNAME:

=head1 SYNOPSIS

To see masternode status:

 % bwk-mn status

To upgrade to the latest version:

 % bwk-mn -U


=head1 DESCRIPTION

Early release. More functionality will be added in the future.


=head1 SEE ALSO

L<cryp-mn>

Other C<cryp-*> in the L<App::cryp> family.
